///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Indoor_Unbalanced_Water_Quality recording.
    /// </summary>
    [TestModule("738d74e1-d4f8-4a75-93b5-c4c10b46cb94", ModuleType.Recording, 1)]
    public partial class Indoor_Unbalanced_Water_Quality : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static Indoor_Unbalanced_Water_Quality instance = new Indoor_Unbalanced_Water_Quality();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Indoor_Unbalanced_Water_Quality()
        {
            PHvalue = "yourValue";
            pHagain = "yourValue";
            Chlorine = "";
            TotalChlorine = "yourValue";
            TotalAlkalinity = "yourValue";
            Calcium = "yourValue";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Indoor_Unbalanced_Water_Quality Instance
        {
            get { return instance; }
        }

#region Variables

        string _PHvalue;

        /// <summary>
        /// Gets or sets the value of variable PHvalue.
        /// </summary>
        [TestVariable("06879e33-d829-4a13-9239-419b9a6f15f6")]
        public string PHvalue
        {
            get { return _PHvalue; }
            set { _PHvalue = value; }
        }

        string _pHagain;

        /// <summary>
        /// Gets or sets the value of variable pHagain.
        /// </summary>
        [TestVariable("f9014ca1-69de-4d20-8b52-110674d7c196")]
        public string pHagain
        {
            get { return _pHagain; }
            set { _pHagain = value; }
        }

        string _Chlorine;

        /// <summary>
        /// Gets or sets the value of variable Chlorine.
        /// </summary>
        [TestVariable("5699501d-7996-4443-a4a7-647847e406d6")]
        public string Chlorine
        {
            get { return _Chlorine; }
            set { _Chlorine = value; }
        }

        string _TotalChlorine;

        /// <summary>
        /// Gets or sets the value of variable TotalChlorine.
        /// </summary>
        [TestVariable("9b67970f-b514-4f52-bcc1-8e94ddfa9aea")]
        public string TotalChlorine
        {
            get { return _TotalChlorine; }
            set { _TotalChlorine = value; }
        }

        string _TotalAlkalinity;

        /// <summary>
        /// Gets or sets the value of variable TotalAlkalinity.
        /// </summary>
        [TestVariable("dabf852a-1877-4d0d-96a5-faa9b8d73509")]
        public string TotalAlkalinity
        {
            get { return _TotalAlkalinity; }
            set { _TotalAlkalinity = value; }
        }

        string _Calcium;

        /// <summary>
        /// Gets or sets the value of variable Calcium.
        /// </summary>
        [TestVariable("91278bfd-d0d5-4f20-bb36-921df0fc7bad")]
        public string Calcium
        {
            get { return _Calcium; }
            set { _Calcium = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '100' with swipe duration'800ms' and step count '0' on item 'ComPentairPentairhome.Sanitizer'.", repo.ComPentairPentairhome.SanitizerInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.Sanitizer.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "100"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "800ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WaterQuality' at Center", repo.ComPentairPentairhome.WaterQualityInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.WaterQuality.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.TESTSTRIP' at Center", repo.ComPentairPentairhome.TESTSTRIPInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.TESTSTRIP.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$PHvalue' on item 'Water_Quality.RCTUITextField'.", repo.Water_Quality.RCTUITextFieldInfo, new RecordItemIndex(4));
            repo.Water_Quality.RCTUITextField.Element.SetAttributeValue("Text", PHvalue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.Chlorine' at Center", repo.Water_Quality.ChlorineInfo, new RecordItemIndex(5));
            repo.Water_Quality.Chlorine.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Water_Quality.TheValidRangeForPHIs59'.", repo.Water_Quality.TheValidRangeForPHIs59Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.Water_Quality.TheValidRangeForPHIs59Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.TextOK' at Center", repo.Water_Quality.TextOKInfo, new RecordItemIndex(7));
            repo.Water_Quality.TextOK.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'Water_Quality.RCTUITextField'.", repo.Water_Quality.RCTUITextFieldInfo, new RecordItemIndex(9));
            repo.Water_Quality.RCTUITextField.Element.SetAttributeValue("Text", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$pHagain' on item 'Water_Quality.RCTUITextField1'.", repo.Water_Quality.RCTUITextField1Info, new RecordItemIndex(10));
            repo.Water_Quality.RCTUITextField1.Element.SetAttributeValue("Text", pHagain);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Chlorine' on item 'Water_Quality.Chlorine'.", repo.Water_Quality.ChlorineInfo, new RecordItemIndex(11));
            repo.Water_Quality.Chlorine.Element.SetAttributeValue("Text", Chlorine);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$TotalChlorine' on item 'Water_Quality.TotalChlorine'.", repo.Water_Quality.TotalChlorineInfo, new RecordItemIndex(12));
            repo.Water_Quality.TotalChlorine.Element.SetAttributeValue("Text", TotalChlorine);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$TotalAlkalinity' on item 'Water_Quality.TotalAlkalinity'.", repo.Water_Quality.TotalAlkalinityInfo, new RecordItemIndex(13));
            repo.Water_Quality.TotalAlkalinity.Element.SetAttributeValue("Text", TotalAlkalinity);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Calcium' on item 'Water_Quality.Calcium'.", repo.Water_Quality.CalciumInfo, new RecordItemIndex(14));
            repo.Water_Quality.Calcium.Element.SetAttributeValue("Text", Calcium);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.TotalAlkalinitylabel' at Center", repo.Water_Quality.TotalAlkalinitylabelInfo, new RecordItemIndex(15));
            repo.Water_Quality.TotalAlkalinitylabel.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.Save' at Center", repo.Water_Quality.SaveInfo, new RecordItemIndex(16));
            repo.Water_Quality.Save.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.CONTINUE' at Center", repo.Water_Quality.CONTINUEInfo, new RecordItemIndex(18));
            repo.Water_Quality.CONTINUE.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(19));
            Delay.Duration(3000, false);
            
            Report.Snapshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.SodiumCarbonate' at Center", repo.Water_Quality.SodiumCarbonateInfo, new RecordItemIndex(21));
            repo.Water_Quality.SodiumCarbonate.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.RecommendCONTINUE' at Center", repo.Water_Quality.RecommendCONTINUEInfo, new RecordItemIndex(22));
            repo.Water_Quality.RecommendCONTINUE.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Water_Quality.RecommendedDosage'.", repo.Water_Quality.RecommendedDosageInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.Water_Quality.RecommendedDosageInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.Save' at Center", repo.Water_Quality.SaveInfo, new RecordItemIndex(24));
            repo.Water_Quality.Save.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(25));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '100' with swipe duration'800ms' and step count '0' on item 'ComPentairPentairhome.Sanitizer'.", repo.ComPentairPentairhome.SanitizerInfo, new RecordItemIndex(26));
            repo.ComPentairPentairhome.Sanitizer.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "100"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "800ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WaterQuality' at Center", repo.ComPentairPentairhome.WaterQualityInfo, new RecordItemIndex(27));
            repo.ComPentairPentairhome.WaterQuality.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.View_Test_history' at Center", repo.Water_Quality.View_Test_historyInfo, new RecordItemIndex(28));
            repo.Water_Quality.View_Test_history.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(29));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.Chemical_level_graph' at Center", repo.Water_Quality.Chemical_level_graphInfo, new RecordItemIndex(30));
            repo.Water_Quality.Chemical_level_graph.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Water_Quality.Hourly_water_history' at Center", repo.Water_Quality.Hourly_water_historyInfo, new RecordItemIndex(31));
            repo.Water_Quality.Hourly_water_history.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(32));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(33));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(34));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(35));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(36));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(38));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(39));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(40));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(41));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(42));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(43));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(44));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(45));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Daily' at Center", repo.ComPentairPentairhome.DailyInfo, new RecordItemIndex(46));
            repo.ComPentairPentairhome.Daily.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(47));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(48));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(49));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(50));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(51));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(52));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(53));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(54));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(55));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(56));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(57));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(58));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(59));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(60));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Weekly' at Center", repo.ComPentairPentairhome.WeeklyInfo, new RecordItemIndex(61));
            repo.ComPentairPentairhome.Weekly.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(62));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(64));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(65));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(66));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(67));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(68));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(69));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(70));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(71));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(72));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(73));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(74));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(75));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Monthly' at Center", repo.ComPentairPentairhome.MonthlyInfo, new RecordItemIndex(76));
            repo.ComPentairPentairhome.Monthly.Touch();
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(77));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(78));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(79));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(80));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(81));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(82));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(83));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(84));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Water_Quality.Screenshot_balanced, false, new RecordItemIndex(85));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Cyanuric_acid_label'.", repo.Water_Quality.Cyanuric_acid_labelInfo, new RecordItemIndex(86));
            repo.Water_Quality.Cyanuric_acid_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Alkanity_Level_Label'.", repo.Water_Quality.Alkanity_Level_LabelInfo, new RecordItemIndex(87));
            repo.Water_Quality.Alkanity_Level_Label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.PH_Level_label'.", repo.Water_Quality.PH_Level_labelInfo, new RecordItemIndex(88));
            repo.Water_Quality.PH_Level_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Down (90°)' starting from 'Center' with distance '150' with swipe duration'600ms' and step count '0' on item 'Water_Quality.Free_chlorine_label'.", repo.Water_Quality.Free_chlorine_labelInfo, new RecordItemIndex(89));
            repo.Water_Quality.Free_chlorine_label.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Down (90°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "150"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "600ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Pool_Add.HomeIcon_without_red' at Center", repo.Pool_Add.HomeIcon_without_redInfo, new RecordItemIndex(90));
            repo.Pool_Add.HomeIcon_without_red.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
