///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("887dd196-2e24-4467-a072-5a65652cc814", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            txtUsername = "qaic123@mailinator.com";
            txtPassword = "Pentair@123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtUsername;

        /// <summary>
        /// Gets or sets the value of variable txtUsername.
        /// </summary>
        [TestVariable("48d7894b-cc5a-4fa3-97b0-dab7bcda12d2")]
        public string txtUsername
        {
            get { return _txtUsername; }
            set { _txtUsername = value; }
        }

        string _txtPassword;

        /// <summary>
        /// Gets or sets the value of variable txtPassword.
        /// </summary>
        [TestVariable("db05bcad-f2c1-4183-ab49-024272ae5d48")]
        public string txtPassword
        {
            get { return _txtPassword; }
            set { _txtPassword = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txtUsername' on item 'ComPentairPentairhome.LoginTextInputEmail'.", repo.ComPentairPentairhome.LoginTextInputEmailInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.LoginTextInputEmail.Element.SetAttributeValue("Text", txtUsername);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txtPassword' on item 'ComPentairPentairhome.LoginTextInputPassword'.", repo.ComPentairPentairhome.LoginTextInputPasswordInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.LoginTextInputPassword.Element.SetAttributeValue("Text", txtPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.LOGIN' at Center", repo.ComPentairPentairhome.LOGINInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.LOGIN.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(3));
            Delay.Duration(30000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'PH_Screen.ReviewNotification' at Center", repo.PH_Screen.ReviewNotificationInfo, new RecordItemIndex(4));
                repo.PH_Screen.ReviewNotification.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesHomeAle' at Center", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesHomeAleInfo, new RecordItemIndex(5));
                repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesHomeAle.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesWhiteLo'.", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesWhiteLoInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesWhiteLoInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Logged In Sucessfully", new RecordItemIndex(8));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
