///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Settings_Product_Overview recording.
    /// </summary>
    [TestModule("421f156a-7926-4fda-a3b1-14d2fc6d6c44", ModuleType.Recording, 1)]
    public partial class Settings_Product_Overview : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static Settings_Product_Overview instance = new Settings_Product_Overview();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Settings_Product_Overview()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Settings_Product_Overview Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable DeviceNamevar.
        /// </summary>
        [TestVariable("082a54eb-1d1a-4bb0-b90f-6f2e64b40f00")]
        public string DeviceNamevar
        {
            get { return repo.DeviceNamevar; }
            set { repo.DeviceNamevar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'Pool_Add.HomeIcon_without_red' at Center", repo.Pool_Add.HomeIcon_without_redInfo, new RecordItemIndex(0));
                repo.Pool_Add.HomeIcon_without_red.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Pool_device_Address' at Center", repo.ComPentairPentairhome.Pool_device_AddressInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.Pool_device_Address.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.HeaderRightImage' at Center", repo.ComPentairPentairhome.HeaderRightImageInfo, new RecordItemIndex(4));
            repo.ComPentairPentairhome.HeaderRightImage.Touch();
            Delay.Milliseconds(300);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Product_Overview.SettingScreen, false, new RecordItemIndex(5));
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (AccessibilityLabel='Product Overview') on item 'Product_Overview.ProductOverviewclick'.", repo.Product_Overview.ProductOverviewclickInfo, new RecordItemIndex(6));
                Validate.AttributeEqual(repo.Product_Overview.ProductOverviewclickInfo, "AccessibilityLabel", "Product Overview", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.ProductOverviewclick' at Center", repo.Product_Overview.ProductOverviewclickInfo, new RecordItemIndex(7));
            repo.Product_Overview.ProductOverviewclick.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Product_Overview.Product_Overview_screen, false, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '250' with swipe duration'800ms' and step count '0' on item 'Product_Overview.Nickname'.", repo.Product_Overview.NicknameInfo, new RecordItemIndex(10));
            repo.Product_Overview.Nickname.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "250"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "800ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Product_Overview.Product_Overview_screen, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.BackArrow' at Center", repo.Product_Overview.BackArrowInfo, new RecordItemIndex(12));
            repo.Product_Overview.BackArrow.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.Notifications' at Center", repo.Product_Overview.NotificationsInfo, new RecordItemIndex(13));
            repo.Product_Overview.Notifications.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(14));
            Delay.Duration(3000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Product_Overview.Notification_screen, false, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Left (180°)' starting from 'Center' with distance '1.0' with swipe duration'500ms' and step count '0' on item 'Product_Overview.RCTView2'.", repo.Product_Overview.RCTView2Info, new RecordItemIndex(16));
            repo.Product_Overview.RCTView2.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Left (180°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "1.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Product_Overview.Notification_screen, false, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.Notification_back_arrow' at Center", repo.Product_Overview.Notification_back_arrowInfo, new RecordItemIndex(19));
            repo.Product_Overview.Notification_back_arrow.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.ContactAProfessional' at Center", repo.Product_Overview.ContactAProfessionalInfo, new RecordItemIndex(20));
            repo.Product_Overview.ContactAProfessional.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(21));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Product_Overview.AssetsSrcCommonFeatureImagesPinLoca'.", repo.Product_Overview.AssetsSrcCommonFeatureImagesPinLocaInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.Product_Overview.AssetsSrcCommonFeatureImagesPinLocaInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Product_Overview.Contact_Pro_back' at CenterLeft", repo.Product_Overview.Contact_Pro_backInfo, new RecordItemIndex(23));
            repo.Product_Overview.Contact_Pro_back.Touch(Location.CenterLeft);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(24));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
