///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WaterTemperature recording.
    /// </summary>
    [TestModule("8ad81dd3-f6c9-454a-8291-9c40df4acdc2", ModuleType.Recording, 1)]
    public partial class WaterTemperature : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest2Repository repository.
        /// </summary>
        public static MyTest2Repository repo = MyTest2Repository.Instance;

        static WaterTemperature instance = new WaterTemperature();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WaterTemperature()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WaterTemperature Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WaterTemperature' at Center", repo.ComPentairPentairhome.WaterTemperatureInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.WaterTemperature.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            // Water Temperature Hourly basis
            Report.Screenshot(ReportLevel.Info, "User", "Hourly Report", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW, false, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Daily' at Center", repo.ComPentairPentairhome.DailyInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.Daily.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "Daily report", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW1, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Weekly' at Center", repo.ComPentairPentairhome.WeeklyInfo, new RecordItemIndex(6));
            repo.ComPentairPentairhome.Weekly.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            // Weekly
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW2, false, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Monthly' at Center", repo.ComPentairPentairhome.MonthlyInfo, new RecordItemIndex(9));
            repo.ComPentairPentairhome.Monthly.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(10));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.ComPentairPentairhome.HistoryHourlyDailyWeeklyMonthly, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AssetsSrcCommonFeatureImagesIconBac' at Center", repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesIconBacInfo, new RecordItemIndex(12));
            repo.ComPentairPentairhome.AssetsSrcCommonFeatureImagesIconBac.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
